# Held-light item IDs for shader uniforms heldItemId / heldItemId2.
# Different IDs allow different brightness/colors.
# 10002 = normal warm bright handheld lights.
# 10003 = redstone torch (dim red).
# 10004 = soul lights (dim cyan/blue).
item.10002 = minecraft:torch minecraft:lantern minecraft:glowstone minecraft:sea_lantern minecraft:shroomlight minecraft:jack_o_lantern minecraft:campfire minecraft:lava_bucket minecraft:glow_berries minecraft:end_rod minecraft:blaze_rod
item.10003 = minecraft:redstone_torch
item.10004 = minecraft:soul_torch minecraft:soul_lantern minecraft:soul_campfire
